services:

  frontend:
    build: ./frontend
    container_name: pvpHB-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev" ]
    networks:
      - pvpHB-network
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: pvphb
      POSTGRES_USER: pvphb
      POSTGRES_PASSWORD: mypass
    container_name: postgres_db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pvphb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pvpHB-network

  backend:
    depends_on:
      - db
    build: ./backend
    container_name: pvpHB-backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: [ "air", "-c", ".air.toml" ]
    networks:
      - pvpHB-network

networks:
  pvpHB-network:
    driver: bridge

volumes:
  postgres_data:
