services:

  frontend:
    build: ./frontend
    container_name: pvpHB-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev" ]
    networks:
      - pvpHB-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: pvpHB-backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: [ "air", "-c", ".air.toml" ]
    networks:
      - pvpHB-network

  db:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: pvphb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  pvpHB-network:
    driver: bridge

volumes:
  postgres_data:
