FROM golang:1.24


# Install goose # Delete Later
RUN go install github.com/pressly/goose/v3/cmd/goose@latest


WORKDIR /app
RUN go install github.com/air-verse/air@latest
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -v -o ./ ./...

CMD ["air","-c",".air.toml"] 
