FROM golang:1.24

WORKDIR /usr/src/app
RUN go install github.com/air-verse/air@latest
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -v -o /usr/local/bin/app ./...

CMD ["air","-c",".air.toml"]
